/**
 * com.inesdata-map:mapper-backend
 * Service responsible for saving a data source mapping and generating the corresponding R2RML / RML mapping file
 *
 * The version of the OpenAPI document: 1.0.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PageableObject } from './pageableObject';
import { SortObject } from './sortObject';
import { SearchOntologyDTO } from './searchOntologyDTO';


export interface PageSearchOntologyDTO { 
    content?: Array<SearchOntologyDTO>;
    empty?: boolean;
    first?: boolean;
    last?: boolean;
    number?: number;
    numberOfElements?: number;
    pageable?: PageableObject;
    size?: number;
    sort?: SortObject;
    totalElements?: number;
    totalPages?: number;
}

