/**
 * com.inesdata-map:mapper-backend
 * Service responsible for saving a data source mapping and generating the corresponding R2RML / RML mapping file
 *
 * The version of the OpenAPI document: 1.0.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { Link } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface ActuatorServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Actuator web endpoint \&#39;health\&#39;
     * 
     */
    health(extraHttpRequestParams?: any): Observable<object>;

    /**
     * Actuator web endpoint \&#39;health-path\&#39;
     * 
     */
    healthPath(extraHttpRequestParams?: any): Observable<object>;

    /**
     * Actuator web endpoint \&#39;info\&#39;
     * 
     */
    info(extraHttpRequestParams?: any): Observable<object>;

    /**
     * Actuator root web endpoint
     * 
     */
    links(extraHttpRequestParams?: any): Observable<{ [key: string]: { [key: string]: Link; }; }>;

    /**
     * Actuator web endpoint \&#39;loggers\&#39;
     * 
     */
    loggers(extraHttpRequestParams?: any): Observable<object>;

    /**
     * Actuator web endpoint \&#39;loggers-name\&#39;
     * 
     * @param name 
     */
    loggersName(name: string, extraHttpRequestParams?: any): Observable<object>;

    /**
     * Actuator web endpoint \&#39;loggers-name\&#39;
     * 
     * @param name 
     * @param body 
     */
    loggersName2(name: string, body?: string, extraHttpRequestParams?: any): Observable<object>;

    /**
     * Actuator web endpoint \&#39;metrics\&#39;
     * 
     */
    metrics(extraHttpRequestParams?: any): Observable<object>;

    /**
     * Actuator web endpoint \&#39;metrics-requiredMetricName\&#39;
     * 
     * @param requiredMetricName 
     */
    metricsRequiredMetricName(requiredMetricName: string, extraHttpRequestParams?: any): Observable<object>;

    /**
     * Actuator web endpoint \&#39;prometheus\&#39;
     * 
     */
    prometheus(extraHttpRequestParams?: any): Observable<object>;

}
