/**
 * com.inesdata-map:mapper-backend
 * Service responsible for saving a data source mapping and generating the corresponding R2RML / RML mapping file
 *
 * The version of the OpenAPI document: 1.0.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { OntologyDTO } from '../model/models';
import { PageSearchOntologyDTO } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface OntologyServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Delete ontology
     * 
     * @param id Ontology identifier to delete
     */
    deleteOntology(id: number, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * List all ontologies
     * 
     * @param page 
     * @param size 
     */
    listOntologies(page: number, size: number, extraHttpRequestParams?: any): Observable<PageSearchOntologyDTO>;

    /**
     * Update given ontology
     * 
     * @param id Ontology identifier to update
     * @param ontologyDTO 
     */
    updateOntology(id: number, ontologyDTO: OntologyDTO, extraHttpRequestParams?: any): Observable<OntologyDTO>;

}
